[package]
name = "primesrs"
version = "0.1.0"
authors = ["Guillermo Lella <arkorott@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rayon = "1.5.0"
libc = "0.2.91"
parking_lot = "0.11.1"
